

[[days]]
name = "Понедельник"


[[days.classes]]
time = "9:50"
subject = "Программирование"
type = "Лабораторная работа"
place = "Кронверкский пр. 49, 2435/3"
lecturer = "Шнейдерис Герардас Герардович"


[[days.classes]]
time = "11:30"
subject = "Программирование"
type = "Лабораторная работа"
place = "Кронверкский пр. 49, 2435/3"
lecturer = "Шнейдерис Герардас Герардович"


[[days]]
name = "Четверг"


[[days.classes]]
time = "13:30"
subject = "История российской науки и техники"
type = "Лекция"
place = "Кронверкский пр. 49, 1404"
lecturer = "Васильев Андрей Владимирович"


[[days.classes]]
time = "15:30"
subject = "История российской науки и техники"
type = "Практика"
place = "Кронверкский пр. 49, 2326"
lecturer = "Васильев Андрей Владимирович"
