version: '3.8'

services:
  balancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "48496:48496/udp"
    depends_on:
      - server1
      - server2

  server1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env.s1:/app/.env:ro
      - ./data:/app/data
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=52
      - LAB_FILE_PATH=/app/data/collection.json

  server2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env.s2:/app/.env:ro
      - ./data:/app/data
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=67
      - LAB_FILE_PATH=/app/data/collection.json