events {
    worker_connections 1024;
}

stream {
    upstream java_udp_backends {
        hash $remote_addr consistent;
        server server1:52;
        server server2:67;
    }

    server {
        listen 48496 udp;
        proxy_pass java_udp_backends;
        proxy_responses 1;
        proxy_timeout 5s;
    }
}