plugins {
    id 'java'
}

group = 'ru.itmo'
version = '1.0'

java {
    sourceCompatibility = '17'
    targetCompatibility = '17'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'org.apache.logging.log4j:log4j-api:2.20.0'
    implementation 'org.apache.logging.log4j:log4j-core:2.20.0'
    implementation 'io.github.cdimascio:dotenv-java:3.0.0'
}

task serverJar(type: Jar) {
    archiveFileName = 'server.jar'

    manifest {
        attributes 'Main-Class': 'ServerMain'
    }

    from sourceSets.main.output
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

task clientJar(type: Jar) {
    archiveFileName = 'client.jar'

    manifest {
        attributes 'Main-Class': 'ClientMain'
    }

    from sourceSets.main.output
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}