version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: local-pg-studs
    restart: always
    environment:
      POSTGRES_DB: studs
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: